cookie:
  expiry_days: 500
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    iaxxon:
      email: alberto@iaxxon.com
      logged_in: false
      name: Iaxxon Energía
      password: iaxxon
      role: admin
    estepa:
      email: concejaliadeportesestepa@gmail.com
      logged_in: false
      name: Ayto. Estepa
      password: iaxxon
      role: estepa
    duplex:
      email: rbriggs@gmail.com
      logged_in: false
      name: Ayto. Estepa
      password: iaxxon
      role: duplex
    colegiodobrasil:
      email: dir@casadobrasil.es
      logged_in: false
      name: Colegio Do Brasil
      password: iaxxon
      role: colegiodobrasil
    aguilardelafrontera:
      email: deportes@aguilardelafrontera.es
      logged_in: false
      name: Ayto. Aguilar de la Frontera
      password: iaxxon
      role: aguilardelafrontera
    priegodecordoba:
      email: vicente.gallego@aytopriegodecordoba.es
      logged_in: false
      name: Ayto. Priego de Córdoba
      password: iaxxon
      role: priegodecordoba
    bodegashabla:
      email: jls@bodegashabla.com
      logged_in: false
      name: Bodegas Habla
      password: iaxxon
      role: bodegashabla

