[influxdb_credentials]
token = "OepRh4h6woJ_yFar3rxWTKhKW9ryBLMpcBLV7T5OE_3dsuJwTJv3rbZLUUkDI3ht1__Wedk_a0E4-126YtcK-g=="
url = "https://eastus-1.azure.cloud2.influxdata.com"
org = "a.marana@equsdesign.com"
bucket1 = "Estepa_Piscina_v3"

